name: Build-Test-Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install project dependencies
      run: npm install
    - name: Running app unit test
      run: npm run test:unit
    - name: Display SoftUni username
      run: echo "braynov"

  CD:
    needs: CI
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to render.com
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
  
  run-app-ui-tests:
    needs: CD
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install project dependencies
      run: npm install
    - name: Install Playwright
      run: npx playwright install
    - name: Running app ui test
      run: npm run test:ui